# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  id: "linkcli"
  main: ./cmd/linkcli/main.go
  binary: build/linkcli
  env:
    - CGO_ENABLED=0
  ldflags:
    - -X github.com/line/link/version.Name=link
    - -X github.com/line/link/version.ServerName=linkd
    - -X github.com/line/link/version.ClientName=linkcli
    - -X github.com/line/link/version.Version={{ .Version }}
    - -X github.com/line/link/version.Commit={{ .FullCommit }}
    - -X "github.com/line/link/version.BuildTags=netgo,ledger"
-
  id: "linkd"
  main: ./cmd/linkd
  binary: build/linkd
  env:
    - CGO_ENABLED=0
  flags:
    - -mod=readonly
    - -tags="netgo ledger"
  ldflags:
    - -X github.com/line/link/version.Name=link
    - -X github.com/line/link/version.ServerName=linkd
    - -X github.com/line/link/version.ClientName=linkcli
    - -X github.com/line/link/version.Version={{ .Version }}
    - -X github.com/line/link/version.Commit={{ .FullCommit }}
    - -X "github.com/line/link/version.BuildTags=netgo,ledger"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - docs/getting-started/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
