version: '3'

services:
  linkdnode0:
    container_name: linkdnode
    image: "line/link"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ${HOME}/.linkd:/root/.linkd
    command: linkd start --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  linkdnode1:
    container_name: lcd
    image: "line/link"
    ports:
      - "1317:1317"
    volumes:
      - ${HOME}/.linkd:/root/.linkd
      - ${HOME}/.linkcli:/root/.linkcli
    command: linkcli rest-server --node=tcp://192.168.10.2:26657  --laddr=tcp://0.0.0.0:1317
    networks:
      localnet:
        ipv4_address: 192.168.10.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
