apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":null,"generation":1,"labels":{"p2p-port":"25656","validator-order":"0"},"name":"validator-p2p-25656-rpc-25657-0","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/validator-1"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"validator-order":"0"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"p2p-port":"25656","validator-order":"0"}},"spec":{"containers":[{"command":["/bin/sh","-ec","while :; do echo '.'; sleep 5 ; done"],"env":[{"name":"ID","value":"0"},{"name":"LOG","value":"linkd.log"}],"image":"golang:1.12.9-alpine3.10","imagePullPolicy":"Always","name":"go","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/linkd","name":"vbs-1tb"}]},{"env":[{"name":"BINARY","value":"/k8s-chain-9400f1b21c19P2P_25656_RPC_25657/binary/linkd"},{"name":"LINKDHOME","value":"/linkd/k8s-chain-9400f1b21c19P2P_25656_RPC_25657/node0/linkd/"},{"name":"ID","value":"0"},{"name":"LOG","value":"linkd.log"}],"image":"docker-registry.linecorp.com/link-network/v2/linkdnode","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/status?","port":25657}},"name":"linkd","ports":[{"containerPort":25656,"protocol":"TCP"},{"containerPort":25657,"protocol":"TCP"},{"containerPort":25658,"protocol":"TCP"}],"readinessProbe":{"initialDelaySeconds":5,"periodSeconds":10,"tcpSocket":{"port":25656}},"resources":{},"securityContext":{"privileged":true},"terminationMessagePath":"/linkd/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/linkd","name":"vbs-1tb"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"nodeSelector":{"validator-order":"0"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/mnt/vdc","type":"Directory"},"name":"vbs-1tb"}]}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    chain-id: k8s-chain-9400f1b21c19P2P_25656_RPC_25657
    p2p-port: "25656"
    validator-order: "0"
  name: validator-p2p-25656-rpc-25657-0
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/validator-p2p-25656-rpc-25657-0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      validator-order: "0"
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        p2p-port: "25656"
        validator-order: "0"
    spec:
      containers:
        - command:
            - /bin/sh
            - -ec
            - while :; do echo '.'; sleep 5 ; done
          env:
            - name: ID
              value: "0"
            - name: LOG
              value: linkd.log
          image: golang:1.12.9-alpine3.10
          imagePullPolicy: Always
          name: go
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /linkd
              name: vbs-1tb
        - env:
            - name: BINARY
              value: /k8s-chain-9400f1b21c19P2P_25656_RPC_25657/binary/linkd
            - name: LINKDHOME
              value: /linkd/k8s-chain-9400f1b21c19P2P_25656_RPC_25657/node0/linkd/
            - name: ID
              value: "0"
            - name: LOG
              value: linkd.log
          image: docker-registry.linecorp.com/link-network/v2/linkdnode
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status?
              port: 25657
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: linkd
          ports:
            - containerPort: 25656
              hostPort: 25656
              protocol: TCP
            - containerPort: 25657
              hostPort: 25657
              protocol: TCP
            - containerPort: 25658
              hostPort: 25658
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 25656
            timeoutSeconds: 1
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /linkd/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /linkd
              name: vbs-1tb
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        validator-order: "0"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /mnt/vdc
            type: Directory
          name: vbs-1tb
status: {}
