# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### genesis state configuration options #####

# default denomination
#
# affected modules:
# - crisis: coin denom for constant fee.
# - governance: coin denom of minimum deposit for a proposal to enter voting period.
# - mint: coin denom to mint.
# - staking: bondable coin denom.
denom = "cony"
