version: '3'

services:
  linkdnode0:
    container_name: linkdnode0
    image: "line/link"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build/node0/linkd:/root/.linkd
    command: linkd start
    networks:
      localnet:
        ipv4_address: 192.168.10.2

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

