version: '3'

services:
  linkdnode0:
    container_name: linkdnode0
    image: "line/link"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build/node0/linkd:/root/.linkd
    command: linkd start
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  linkdnode1:
    container_name: linkdnode1
    image: "line/link"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./build/node1/linkd:/root/.linkd
    command: linkd start
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  linkdnode2:
    container_name: linkdnode2
    image: "line/link"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/node2/linkd:/root/.linkd
    command: linkd start
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  linkdnode3:
    container_name: linkdnode3
    image: "line/link"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/node3/linkd:/root/.linkd
    command: linkd start
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

