# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &linux_defaults
  working_directory: /go/src/github.com/line/link
  docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: 'on'

machine_defaults: &machine_defaults
  working_directory: /home/circleci/.go_workspace/src/github.com/line/link
  machine:
    image: circleci/classic:latest
    docker_layer_caching: true
  environment:
    GOPATH: /home/circleci/.go_workspace/
    GOOS: linux
    GOARCH: amd64
    GO_VERSION: "1.12.5"


jobs:
  fmt:
    <<: *linux_defaults
    steps:
      - checkout
      - run:
          name: check formatting
          command: if [[ -n "$(gofmt -l .)" ]]; then gofmt -l .; exit 1; fi

  setup_dependencies:
    <<: *linux_defaults
    steps:
      - run: mkdir -p /tmp/workspace/bin
      - run: mkdir -p /tmp/workspace/profiles
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-mod-{{ checksum "go.sum" }}
      - run:
          name: binaries
          command: |
            export PATH=/tmp/workspace/bin:$PATH
            make go-mod-cache
            make install
      - save_cache:
          key: dependency-cache-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: tools
          command: |
            make get-tools
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bin
  unit_test:
    <<: *linux_defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-mod-{{ checksum "go.sum" }}
      - run:
          name: Test unittest
          command: |
            make check-unit
  integration_test:
    <<: *linux_defaults
    parallelism: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-mod-{{ checksum "go.sum" }}
      - run:
          name: Test cli
          command: |
            export BUILDDIR=`pwd`/build
            make check-build
  setup_docker_and_binary:
    <<: *machine_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - machine-dependency-cache-mod-{{ checksum "go.sum" }}-1.12.5
      - run:
          name: run setup go
          command: |
            set -x
            if [ "$(go version)" != "go version go1.12.5 linux/amd64" ]; then
                mkdir -p /tmp/gobinary
                pushd /tmp/gobinary
                wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz
                sudo tar -xvf go$GO_VERSION.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go
                sudo cp -r go /usr/local
                popd
            fi
      - run:
          name: build binaries
          command: |
            set -x
            make build-linux
            make build
      - save_cache:
          key: machine-dependency-cache-mod-{{ checksum "go.sum" }}-1.12.5
          paths:
            - "/home/circleci/.go_workspace/pkg/mod"
            - "/tmp/gobinary"


  integration_multi_node_test:
    <<: *machine_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - machine-dependency-cache-mod-{{ checksum "go.sum" }}-1.12.5
      - run:
          name: copy go compiler
          command: |
            set -x
            pushd /tmp/gobinary
            sudo rm -rf /usr/local/go
            sudo mv go /usr/local
            popd
      - run:
          name: build binary
          command: |
            set -x
            make build
      - run:
          name: build docker image
          command: |
            set -x
            make build-docker-integration
      - run:
          name: run integration test for multi node and exit on failure
          command: |
            set -x
            docker network prune -f
            make check-build-integration
  localnet:
    <<: *machine_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - machine-dependency-cache-mod-{{ checksum "go.sum" }}-1.12.5
      - run:
          name: copy go compiler
          command: |
            set -x
            pushd /tmp/gobinary
            sudo rm -rf /usr/local/go
            sudo mv go /usr/local
            popd
      - run:
          name: build binaries for linux
          command: |
            set -x
            make build-linux
      - run:
          name: build docker image
          command: |
            set -x
            make build-docker-testnet
            make build-conf-testnet
      - run:
          name: run localnet and exit on failure
          command: |
            set -x
            docker network prune -f
            make start-testnet
            ./contrib/localnet-blocks-test.sh 40 5 10 localhost

workflows:
  version: 2
  build_and_test:
    jobs:
      - fmt
      - setup_dependencies:
          requires:
            - fmt
      - setup_docker_and_binary:
          requires:
            - fmt
      - unit_test:
          requires:
            - setup_dependencies
      - integration_test:
          requires:
            - setup_dependencies
      - localnet:
          requires:
            - setup_docker_and_binary
      - integration_multi_node_test:
          requires:
            - setup_docker_and_binary

