# Test Config
msgs_per_tx_prepare: 2000
max_gas_prepare: 110000000
msgs_per_tx_load_test: 3
max_gas_load_test: 120000
tps: 200
duration: 30
ramp_up_time: 10
throughput_threshold: -1
latency_threshold: -1
tps_threshold: -1
max_workers: 50
output: "/link-load-tester/contrib/load_test"

# Test Target Info
target_url: "http://lcd:1317"
chain_id: "link"
coin_name: "stake"
testnet: true

# Master & Slaves Info
master_mnemonic: "tray echo noodle shop seed regret slush camp canvas crunch inflict stool fit length misery prevent borrow pact speed choose phrase ranch daughter boring"
slaves:
  slave1:
    url: "http://slave:8000"
    mnemonic: "fever tell fancy ridge fly glow reflect decline voice coil reflect ski empty forum frost rebuild slide nut invite chase swarm flag dizzy diet"
    scenario: "tx_send"
    params: []
#  slave2:
#    url: "http://hostaddr:8000"
#    mnemonic: "tribe slot pioneer either light fossil broken scissors okay special update place want trash soldier rural portion lock couple venue cushion bind enact one"
#    scenario: "tx_send"
#    params: []
#  ...
