# Test Config
msgs_per_tx_prepare: 2000
msgs_per_tx_load_test: 3
tps: 200
duration: 30
max_workers: 50
pacer_type: "constant"
output: "./results"

# Test Target Info
target_url: "http://host.docker.internal:1317"
chain_id: "link"
coin_name: "stake"

# Master & Slaves Info
master_mnemonic: "tray echo noodle shop seed regret slush camp canvas crunch inflict stool fit length misery prevent borrow pact speed choose phrase ranch daughter boring"
slaves:
  slave1:
    url: "http://localhost:8000"
    mnemonic: "fever tell fancy ridge fly glow reflect decline voice coil reflect ski empty forum frost rebuild slide nut invite chase swarm flag dizzy diet"
    target_type: "tx_send"
#  slave2:
#    url: "http://hostaddr:8000"
#    mnemonic: "tribe slot pioneer either light fossil broken scissors okay special update place want trash soldier rural portion lock couple venue cushion bind enact one"
#    target_type: "tx_send"
#  ...
