FROM debian:stable

RUN apt-get update && \
  apt-get -y upgrade && \
  apt-get -y install curl jq

USER @UID@:@GID@
EXPOSE 26656 26657
ENTRYPOINT ["/etc/init"]
CMD ["start", "--log_format", "plain"]
STOPSIGNAL SIGTERM

COPY init /etc/init
COPY simd /usr/bin/simd
