FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install jq -y

RUN addgroup --gid @DAEMON_GID@ @DAEMON_NAME@
RUN adduser --home @DAEMON_HOME@ --uid @DAEMON_UID@ --gid @DAEMON_GID@ --gecos "" --disabled-password @DAEMON_NAME@
ENTRYPOINT ["/etc/init"]
CMD ["start", "--log_format", "plain"]
STOPSIGNAL SIGTERM

COPY init /etc/init
COPY binaries /usr/local/bin/

RUN mkdir @DAEMON_SYNCDIR@ && chown @DAEMON_NAME@ @DAEMON_SYNCDIR@

USER @DAEMON_NAME@
WORKDIR @DAEMON_HOME@
