FROM debian:stable

RUN apt-get update && apt-get -y upgrade

RUN addgroup --gid @SIMD_GID@ simd
RUN adduser --home @SIMD_WORKDIR@ --uid @SIMD_UID@ --gid @SIMD_GID@ --gecos "" --disabled-password simd
ENTRYPOINT ["/etc/init"]
CMD ["start", "--log_format", "plain"]
STOPSIGNAL SIGTERM

COPY init /etc/init
COPY simd /usr/bin/simd

RUN mkdir @SIMD_SYNCDIR@ && chown simd @SIMD_SYNCDIR@

USER simd
WORKDIR @SIMD_WORKDIR@
