#!/bin/sh

set -e

# every variable must not be empty
assert_variables() {
	for name in $@
	do
		if [ -z "$(eval echo '$'$name)" ]
		then
			echo no variable: $name
			false
		fi
	done
}

assert_variables DAEMON_NAME \
				 DAEMON_HOME \
				 DAEMON_ALLOW_DOWNLOAD_BINARIES

if [ ! -f initialized ]
then
	setup
	date >initialized
fi

cosmovisor run start
