name: Testing secrets visibility
on:
  pull_request:
jobs:
  # test-codecov:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: echo FOUND
  #     if: "${{ secrets.CODECOV_TOKEN != null }}"
  test-github:
    runs-on: ubuntu-latest
    steps:
    - run: echo FOUND
      if: "${{ secrets.GITHUB_TOKEN != null }}"
